# Generated by Django 4.1.5 on 2023-02-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_rating_delete_empleyee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Working_Day_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days_times', to='employee.employee')),
            ],
        ),
    ]
