# Generated by Django 4.1.5 on 2023-02-12 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_working_day_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_working_day_time',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_working_day_time',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
