# Generated by Django 4.1.7 on 2023-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_working_day_time_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
