# Generated by Django 4.1.7 on 2023-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_address_employee_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
