# Generated by Django 4.1.7 on 2023-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_start_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
