# Generated by Django 4.1.7 on 2023-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_job_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
