# Generated by Django 4.1.7 on 2023-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_job_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
