# Generated by Django 4.2.4 on 2023-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_working_day_time',
            name='day_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
