# Generated by Django 4.2.4 on 2023-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_working_day_time_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_working_day_time',
            name='day_number',
            field=models.SmallIntegerField(),
        ),
    ]
