# Generated by Django 4.1.5 on 2023-02-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_employee_working_day_time_created_date_and_more'),
        ('service', '0002_service_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('duration', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='CCCCCC', max_length=7)),
                ('done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=models.SET(1), related_name='app_employees', to='employee.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_services', to='service.service')),
            ],
        ),
    ]
