# Generated by Django 4.2.4 on 2023-08-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_employee',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
