# Generated by Django 4.2.4 on 2023-08-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_employee_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_employee',
            name='duration',
        ),
    ]
